### PR TITLE
Features/update esys oemof b3 v0.0.4

### PR DESCRIPTION
**Pull request by MaGering**
Updates the esys to newest release of oemof-B3 and hence to fixed tabular version.

## Before merging into `dev`-branch, please make sure that the following points are checked:

- [ ] All pre-commit tests passed locally with: `pre-commit run -a`
- [ ] File `CHANGELOG.md` was updated
- [ ] The docs were updated
  - [ ] if `dataset.md`s were updated, the dataset docs were regenerated using
    `python docs/generate_dataset_mds.py`

If packages were modified:
- [ ] File `poetry.lock` was updated with: `poetry lock`
- [ ] A new env was successfully set up

WARNING: When modifying use snakemake <=7.32.0, cf. #186

If data flow was adjusted:
- [ ] Data pipeline run finished successfully with: `snakemake -jX`
- [ ] Esys appdata was created successfully with: `snakemake -jX make_esys_appdata`

  (with `X` =  desired number of cores, e.g. 1)

### CODE REVIEW

**Comment by MaGering** [comment]
@nesnoj: Can we switch to python 3.10 in the env?
(Further questions of this kind will arise I'm sure)

**Review by nesnoj — COMMENTED** [review]
Thx @MaGering!
If I get this right, it's the same esys as in DP - these changes are to make it work with the current versions, right?

@henhuy I guess you haven't tried to use it with the epp app yet and you need me to generate the datapackage?

**Comment by nesnoj** [comment]
> @nesnoj: Can we switch to python 3.10 in the env? (Further questions of this kind will arise I'm sure)

I was a bit worried because snakemake version is currently pinned https://github.com/rl-institut/digipipe/pull/187.  According to the [requirements for snakemake 7.32](https://github.com/snakemake/snakemake/blob/v7.32.0/pyproject.toml) python 3.10 seems to be supported. But it needs to be tested as many other packages will be updated as well I guess. Is it crucial for further steps in this PR?
I opened a separate issue: #14

**Comment by MaGering** [comment]
> > @nesnoj: Can we switch to python 3.10 in the env? (Further questions of this kind will arise I'm sure)
> 
> I was a bit worried because snakemake version is currently pinned [rl-institut/digipipe#187](https://github.com/rl-institut/digipipe/pull/187). According to the [requirements for snakemake 7.32](https://github.com/snakemake/snakemake/blob/v7.32.0/pyproject.toml) python 3.10 seems to be supported. But it needs to be tested as many other packages will be updated as well I guess. Is it crucial for further steps in this PR? I opened a separate issue: #14

Thanks for looking into that. Yes, since oemof.tabular requires `python_requires=">=3.9, <3.11"`. and oemof-B3 requires `python = ">=3.10, <3.11"`. The newest release of oemof-B3 does not support 3.9.

**Comment by MaGering** [comment]
> Thx @MaGering!
> If I get this right, it's the same esys as in DP - these changes are to make it work with the current versions, right?

Not quite. I restructured the esys as in DP. But mainly this PR is to import changes which were made in release v0.0.4 of oemof-B3. With this PR the oemof.tabular version fits the one, which @henhuy is using in the web app.

**Comment by nesnoj** [comment]
I changed the base to new SLE project branch

**Pull request merged**
